In [1]:
import pandas as pd

df = pd.read_pickle('/Users/jacknugent/Desktop/yale_chemistry_project/alberts_nmr_qchem_merged.pkl')

In [2]:
df.columns

Index(['h_nmr_peaks', 'h_nmr_spectra', 'molecular_formula', 'c_nmr_peaks',
       'c_nmr_spectra', 'canonical_smiles', 'hex_id', 'Filename', 'name',
       'homo_ev', 'lumo_ev', 'gap_ev', 'ionization_ev', 'elec_affinity_ev',
       'hardness', 'chem_potential', 'electrophil_index'],
      dtype='string')

In [5]:
df['h_nmr_peaks'][0]

array([{'category': 'dd', 'centroid': 8.167766586790638, 'delta': 8.167985042353635, 'j_values': '1.1822509765625_8.5074462890625_', 'nH': 1, 'rangeMax': 8.195066386110536, 'rangeMin': 8.14111342890133},
       {'category': 'dp', 'centroid': 8.040799833213576, 'delta': 8.041281133605485, 'j_values': '1.3280029296875_11.341552734375_', 'nH': 1, 'rangeMax': 8.075308885116417, 'rangeMin': 8.007417820556068},
       {'category': 'dd', 'centroid': 7.60009653622557, 'delta': 7.59930679025003, 'j_values': '8.5762939453125_11.3846435546875_', 'nH': 1, 'rangeMax': 7.636584921674536, 'rangeMin': 7.562095287127875},
       {'category': 'd', 'centroid': 2.9958349044386225, 'delta': 2.996904468068841, 'j_values': '7.015625_', 'nH': 2, 'rangeMax': 3.021207339688096, 'rangeMin': 2.9726015964495858},
       {'category': 'dp', 'centroid': 2.0865922010954563, 'delta': 2.0867241508223207, 'j_values': '7.27630615234375_14.4627685546875_', 'nH': 1, 'rangeMax': 2.147388737901591, 'rangeMin': 2.026040356234845},
       {'category': 'd', 'centroid': 0.9377233162846028, 'delta': 0.9373660223648432, 'j_values': '7.310455322265625_', 'nH': 6, 'rangeMax': 0.9619636875774944, 'rangeMin': 0.912768357152192}],
      dtype=object)

In [8]:
df['c_nmr_peaks'][0]

array([{'delta (ppm)': 171.4319391367614, 'integral': 0.0009463989416141, 'intensity': 0.0502412143905301, 'width (ppm)': 0.0119620083281718},
       {'delta (ppm)': 162.6553065346315, 'integral': 0.0009463989400797, 'intensity': 0.0502412070898473, 'width (ppm)': 0.0119620083281718},
       {'delta (ppm)': 161.0071842566587, 'integral': 0.0009463988997302, 'intensity': 0.0502412145119212, 'width (ppm)': 0.0119620083281718},
       {'delta (ppm)': 149.04867499228726, 'integral': 0.0001233313504412, 'intensity': 0.0065637118859719, 'width (ppm)': 0.0119620083281718},
       {'delta (ppm)': 149.0143647700196, 'integral': 0.0003541401419941, 'intensity': 0.0189005600409519, 'width (ppm)': 0.0119620083281718},
       {'delta (ppm)': 148.98002888936148, 'integral': 0.0003605412678464, 'intensity': 0.0191352804859308, 'width (ppm)': 0.0119620083281718},
       {'delta (ppm)': 148.9456930087034, 'integral': 0.0001235303976944, 'intensity': 0.0065743052088925, 'width (ppm)': 0.0119620083281718},
       {'delta (ppm)': 128.3498872606233, 'integral': 0.0002085638292563, 'intensity': 0.0110997964440944, 'width (ppm)': 0.0119620083281718},
       {'delta (ppm)': 128.323181575667, 'integral': 0.0006146569486812, 'intensity': 0.032613969509065, 'width (ppm)': 0.0119620083281718},
       {'delta (ppm)': 128.29647589071075, 'integral': 0.0006098340308388, 'intensity': 0.0324554532352465, 'width (ppm)': 0.0119620083281718},
       {'delta (ppm)': 128.2697702057544, 'integral': 0.0002085608270974, 'intensity': 0.0110996366687773, 'width (ppm)': 0.0119620083281718},
       {'delta (ppm)': 127.75097797510564, 'integral': 0.0001181894776856, 'intensity': 0.0062794396826651, 'width (ppm)': 0.0119620083281718},
       {'delta (ppm)': 126.2153996550884, 'integral': 0.001608675562987, 'intensity': 0.0854002103716616, 'width (ppm)': 0.0119620083281718},
       {'delta (ppm)': 125.87762505334838, 'integral': 0.000211554675393, 'intensity': 0.0112589696978256, 'width (ppm)': 0.0119620083281718},
       {'delta (ppm)': 125.84909061935878, 'integral': 0.0005980055833413, 'intensity': 0.0320454467960827, 'width (ppm)': 0.0119620083281718},
       {'delta (ppm)': 125.82047738547703, 'integral': 0.0006104059774706, 'intensity': 0.0324365344192798, 'width (ppm)': 0.0119620083281718},
       {'delta (ppm)': 125.79186415159528, 'integral': 0.000212030985645, 'intensity': 0.011284318996694, 'width (ppm)': 0.0119620083281718},
       {'delta (ppm)': 125.55920703973176, 'integral': 0.0003548782782462, 'intensity': 0.0188407502960465, 'width (ppm)': 0.0119620083281718},
       {'delta (ppm)': 124.76948517382998, 'integral': 0.0001180282318837, 'intensity': 0.0062713915851169, 'width (ppm)': 0.0119620083281718},
       {'delta (ppm)': 124.51577587083273, 'integral': 0.0003546624004187, 'intensity': 0.0188290694271692, 'width (ppm)': 0.0119620083281718},
       {'delta (ppm)': 124.26206852467216, 'integral': 0.0003547069773355, 'intensity': 0.0188331221033704, 'width (ppm)': 0.0119620083281718},
       {'delta (ppm)': 124.0083614159914, 'integral': 0.0001180900218834, 'intensity': 0.006276108258959, 'width (ppm)': 0.0119620083281718},
       {'delta (ppm)': 123.36933635027502, 'integral': 0.0003549053674888, 'intensity': 0.0188408177438521, 'width (ppm)': 0.0119620083281718},
       {'delta (ppm)': 121.17756267596712, 'integral': 0.000118204703411, 'intensity': 0.0062805865610428, 'width (ppm)': 0.0119620083281718},
       {'delta (ppm)': 118.89414813214178, 'integral': 0.0001238440348301, 'intensity': 0.0065909970215443, 'width (ppm)': 0.0119620083281718},
       {'delta (ppm)': 118.86174579289388, 'integral': 0.0003519465041336, 'intensity': 0.0188450374500759, 'width (ppm)': 0.0119620083281718},
       {'delta (ppm)': 118.82740302477852, 'integral': 0.0003597398053767, 'intensity': 0.019115499909409, 'width (ppm)': 0.0119620083281718},
       {'delta (ppm)': 118.79497469304587, 'integral': 0.0001245300014333, 'intensity': 0.0066275042610322, 'width (ppm)': 0.0119620083281718},
       {'delta (ppm)': 107.23528759959918, 'integral': 0.0009463989500096, 'intensity': 0.0502412151567918, 'width (ppm)': 0.0119620083281718},
       {'delta (ppm)': 44.02674640710993, 'integral': 0.0022713578816128, 'intensity': 0.1205789262002486, 'width (ppm)': 0.0119620083281718},
       {'delta (ppm)': 27.95564670968846, 'integral': 0.0016088783381612, 'intensity': 0.0854100662055996, 'width (ppm)': 0.0119620083281718},
       {'delta (ppm)': 22.05369033383628, 'integral': 0.0058676736274337, 'intensity': 0.3114955226896387, 'width (ppm)': 0.0119620083281718}],
      dtype=object)

In [3]:
df = df.reset_index(drop = True)

In [4]:
print(df.dtypes)

h_nmr_peaks           object
h_nmr_spectra         object
molecular_formula     string
c_nmr_peaks           object
c_nmr_spectra         object
canonical_smiles      string
hex_id                object
Filename              string
name                  string
homo_ev              float64
lumo_ev              float64
gap_ev               float64
ionization_ev        float64
elec_affinity_ev     float64
hardness             float64
chem_potential       float64
electrophil_index    float64
dtype: object

In [7]:
df = df.dropna(subset=["h_nmr_peaks", "c_nmr_peaks", "gap_ev"])

In [8]:
df.describe()

,homo_ev,lumo_ev,gap_ev,ionization_ev,elec_affinity_ev,hardness,chem_potential,electrophil_index
count,9599.000000,9599.000000,9599.000000,9599.000000,9599.000000,9599.000000,9599.000000,9599.000000
mean,-8.131548,0.618461,8.750010,8.131548,-0.618461,4.375005,-3.756544,1.677990
std,0.599081,0.825669,0.979253,0.599081,0.825669,0.489626,0.529698,0.532415
min,-10.421965,-2.589709,4.541038,6.167735,-3.782384,2.270519,-6.025147,0.290843
25%,-8.533358,0.046259,8.084642,7.706403,-1.114035,4.042321,-4.102866,1.301344
50%,-8.091309,0.537153,8.608053,8.091309,-0.537153,4.304027,-3.759254,1.645517
75%,-7.706403,1.114035,9.271467,8.533358,-0.046259,4.635733,-3.412377,2.017495
max,-6.167735,3.782384,13.547466,10.421965,2.589709,6.773733,-1.766564,5.283517

In [9]:
'''
An 2014 h nmr features
'''

'\nAn 2014 h nmr features\n'

In [10]:
import pandas as pd

from an2014_nmr import (
    all_broadness_columns,
    all_integration_columns,
    an2014_features_from_peaks,
    full_descriptor_columns,
    mlr_feature_columns,
)

an14_df = pd.DataFrame(
    # apply to all rows
    df.apply(lambda row: an2014_features_from_peaks(row["h_nmr_peaks"]), axis=1).tolist()
)

df_an = pd.concat([df.reset_index(drop=True), an14_df], axis=1)

an14_full_cols = full_descriptor_columns()
an14_mlr_cols = mlr_feature_columns()

print(df_an[an14_mlr_cols + ["an14_total_nH"]].head())

   an14_x0.5  an14_x1  an14_x1.5  an14_x2  an14_x4.5  an14_x5  an14_x5.5  \
0        0.0      6.0        0.0      0.0        0.0      0.0        0.0
1        0.0      0.0        0.0      0.0        1.0      0.0        0.0
2        0.0      0.0        0.0      0.0        2.0      0.0        0.0
3        0.0      0.0        0.0      0.0        0.0      0.0        2.0
4        0.0      0.0        0.0      0.0        0.0      0.0        0.0

   an14_x6.5  an14_x7  an14_x7.5  an14_b1  an14_b2  an14_b3  an14_total_nH
0        0.0      0.0        0.0      0.0      0.0      0.0           12.0
1        0.0      0.0        2.0      0.0      0.0      0.0           17.0
2        0.0      0.0        6.0      0.0      0.0      0.0           16.0
3        0.0      4.0        3.0      0.0      0.0      0.0           17.0
4        0.0      0.0        9.0      0.0      0.0      0.0           17.0

In [11]:
'''
now 13c features
'''

'\nnow 13c features\n'

In [12]:
from add_c_nmr_bins import process_row

c13_df = pd.DataFrame(
    # apply to all rows
    df.apply(process_row, axis=1).tolist()
)

print(c13_df.head())

   c_x10  c_x20  c_x30  c_x40  c_x50  c_x60  c_x70  c_x80  c_x90  c_x100  ...  \
0    0.0    0.0    1.0    0.0    0.0    0.0    0.0    0.0    0.0     0.0  ...
1    0.0    0.0    0.0    0.0    0.0    1.0    0.0    0.0    0.0     0.0  ...
2    0.0    0.0    0.0    1.0    0.0    0.0    0.0    0.0    0.0     0.0  ...
3    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0     0.0  ...
4    0.0    0.0    0.0    1.0    0.0    0.0    0.0    0.0    0.0     0.0  ...

   c_x165  c_x175  c_x185  c_x195  c_x205  c_x215  c_b1  c_b2  c_b3  \
0     2.0     1.0     0.0     0.0     0.0     0.0   0.0   0.0   0.0
1     1.0     0.0     0.0     0.0     0.0     0.0   0.0   0.0   0.0
2     0.0     0.0     0.0     0.0     0.0     0.0   0.0   0.0   0.0
3     0.0     0.0     0.0     0.0     0.0     0.0   0.0   0.0   0.0
4     0.0     0.0     0.0     0.0     0.0     0.0   0.0   0.0   0.0

   c_total_nC
0        32.0
1        24.0
2        16.0
3        14.0
4        12.0

[5 rows x 48 columns]

In [13]:
'''
now our NMF features
'''

'\nnow our NMF features\n'

In [14]:
import pickle
import numpy as np
from create_nmr_dictionary_features import (
    build_soft_peak_matrix, _apply_transform, _invert_transform
)


# load our pretrained nmf model
path = "/Users/jacknugent/Downloads/ids_nmr_1k_dictionary_model.pkl"
with open(path, "rb") as f:
    model_artifact = pickle.load(f)

nmf_model = model_artifact["nmf_model"]
config    = model_artifact["config"]
h_grid    = model_artifact["h_grid_ppm"]
c_grid    = model_artifact["c_grid_ppm"]

#build our soft peak vectors
h_matrix = build_soft_peak_matrix(
    df["h_nmr_peaks"], h_grid, config["h_sigma_ppm"], modality="h",
    width_scale=config["h_width_scale"], use_peak_width=config["use_peak_width"]
)
c_matrix = build_soft_peak_matrix(
    df["c_nmr_peaks"], c_grid, config["c_sigma_ppm"], modality="c",
    width_scale=config["c_width_scale"], use_peak_width=config["use_peak_width"]
)

# apply nmf scaling
h_t = _apply_transform(h_matrix, config["intensity_transform"])
c_t = _apply_transform(c_matrix, config["intensity_transform"])
x = np.concatenate([config["h_modality_weight"] * h_t, config["c_modality_weight"] * c_t], axis=1)

# apply nmf to our new data not fit
codes = nmf_model.transform(x)

# buid nmf df with the same column names as the model built bc there are multiple possible no of columsn
code_columns = model_artifact["feature_columns"]
nmf_df = pd.DataFrame(codes, columns=code_columns, index=df.index)

# h and c components 
h_comp = model_artifact["h_components"]
c_comp = model_artifact["c_components"]
# reconstructed components unnormalized
h_recon = _invert_transform(codes @ h_comp, config["intensity_transform"])
c_recon = _invert_transform(codes @ c_comp, config["intensity_transform"])

# calculate recon error by minusing the actual components by the reconstructed ones
nmf_df["nmr_h_reconstruction_error"] = np.linalg.norm(h_matrix - h_recon, axis=1)
nmf_df["nmr_c_reconstruction_error"] = np.linalg.norm(c_matrix - c_recon, axis=1)
nmf_df["nmr_total_reconstruction_error"] = (
    nmf_df["nmr_h_reconstruction_error"] + nmf_df["nmr_c_reconstruction_error"]
)

print(f"NMF features: {nmf_df.shape[1]} columns")
print(f"Avg H recon error: {nmf_df['nmr_h_reconstruction_error'].mean():.4f}")
print(f"Avg C recon error: {nmf_df['nmr_c_reconstruction_error'].mean():.4f}")

/Users/jacknugent/Desktop/yale_chemistry_project/.venv/lib/python3.13/site-packages/sklearn/base.py:525: InconsistentVersionWarning: Trying to unpickle estimator NMF from version 1.7.1 when using version 1.9.0. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
  warnings.warn(

NMF features: 35 columns
Avg H recon error: 0.1169
Avg C recon error: 0.1469

In [15]:
nmf_df.describe()

,nmr_dict_code_00,nmr_dict_code_01,nmr_dict_code_02,nmr_dict_code_03,nmr_dict_code_04,nmr_dict_code_05,nmr_dict_code_06,nmr_dict_code_07,nmr_dict_code_08,nmr_dict_code_09,...,nmr_dict_code_25,nmr_dict_code_26,nmr_dict_code_27,nmr_dict_code_28,nmr_dict_code_29,nmr_dict_code_30,nmr_dict_code_31,nmr_h_reconstruction_error,nmr_c_reconstruction_error,nmr_total_reconstruction_error
count,9.599000e+03,9.599000e+03,9.599000e+03,9.599000e+03,9.599000e+03,9.599000e+03,9.599000e+03,9.599000e+03,9.599000e+03,9.599000e+03,...,9.599000e+03,9.599000e+03,9.599000e+03,9.599000e+03,9.599000e+03,9.599000e+03,9.599000e+03,9599.000000,9599.000000,9599.000000
mean,1.599478e+00,1.780246e+00,1.729683e+00,1.903050e+00,1.678410e+00,1.710623e+00,1.771806e+00,1.859672e+00,1.795765e+00,1.935274e+00,...,1.960592e+00,2.062769e+00,1.887041e+00,1.827203e+00,1.656094e+00,1.740577e+00,1.794937e+00,0.116879,0.146913,0.263793
std,2.559235e+00,4.233931e+00,2.895367e+00,4.490028e+00,2.934648e+00,3.295412e+00,2.933267e+00,4.849907e+00,3.251878e+00,3.206932e+00,...,3.051059e+00,3.012527e+00,2.999331e+00,3.076970e+00,3.318095e+00,3.721486e+00,3.077676e+00,0.037960,0.034320,0.065359
min,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.030093,0.077428,0.124998
25%,5.765142e-12,1.428679e-37,1.691749e-35,0.000000e+00,2.300231e-42,3.388317e-15,6.767724e-16,0.000000e+00,3.672311e-24,1.332805e-13,...,3.935056e-22,4.132429e-07,1.394548e-34,3.974382e-29,3.113616e-37,1.724310e-26,1.353012e-34,0.090098,0.122263,0.216335
50%,3.702708e-01,1.016319e-19,2.824649e-09,1.649031e-34,1.429735e-14,2.891995e-03,8.383414e-02,7.696459e-33,1.175149e-09,3.770732e-02,...,4.346398e-02,7.998250e-01,5.558867e-04,6.267794e-12,1.854906e-17,3.822141e-19,1.055822e-04,0.110193,0.139504,0.251012
75%,2.304414e+00,1.039792e+00,2.717890e+00,2.125578e-01,2.618379e+00,2.162658e+00,2.561282e+00,4.702942e-04,2.381104e+00,2.717418e+00,...,3.030533e+00,3.088303e+00,2.822106e+00,2.870152e+00,2.328757e+00,2.037020e+00,2.686609e+00,0.136075,0.165022,0.297939
max,2.604317e+01,3.392091e+01,2.628810e+01,3.196887e+01,3.281079e+01,3.523095e+01,2.371850e+01,4.960652e+01,2.859795e+01,2.741711e+01,...,3.336768e+01,3.113490e+01,2.461790e+01,3.355259e+01,3.805479e+01,3.674381e+01,3.810706e+01,0.315666,0.372549,0.613693

In [16]:
'''
Muellers et al 202X features
'''

'\nMuellers et al 202X features\n'

In [17]:
from scipy.stats import skew, kurtosis

def safe_stat(peaks, key, func):
    vals = [p[key] for p in peaks] if len(peaks) > 0 else []
    if len(vals) == 0: 
        return np.nan
    return func(vals)

# Number of shifts
df['num_delta_13C'] = df['c_nmr_peaks'].apply(len)
df['num_delta_1H']  = df['h_nmr_peaks'].apply(len)

# Maximum shifts
df['max_delta_13C'] = df['c_nmr_peaks'].apply(lambda p: safe_stat(p, 'delta (ppm)', np.max))
df['max_delta_1H']  = df['h_nmr_peaks'].apply(lambda p: safe_stat(p, 'delta', np.max))

# Mean 13C shift
df['mean_delta_13C'] = df['c_nmr_peaks'].apply(lambda p: safe_stat(p, 'delta (ppm)', np.mean))

# Skewness
df['skew_delta_13C'] = df['c_nmr_peaks'].apply(lambda p: safe_stat(p, 'delta (ppm)', lambda v: skew(v) if len(v) >= 3 else np.nan))
df['skew_delta_1H']  = df['h_nmr_peaks'].apply(lambda p: safe_stat(p, 'delta', lambda v: skew(v) if len(v) >= 3 else np.nan))

# Kurtosis 13C
df['kurt_delta_13C'] = df['c_nmr_peaks'].apply(lambda p: safe_stat(p, 'delta (ppm)', lambda v: kurtosis(v) if len(v) >= 4 else np.nan))

In [18]:
#combine all features to one big df
df = pd.concat([df.reset_index(drop=True), an14_df, c13_df, nmf_df], axis=1)

In [21]:
df.to_pickle('/Users/jacknugent/Downloads/alberts_nmr_qchem_merged.pkl')

In [22]:
df.describe()

,homo_ev,lumo_ev,gap_ev,ionization_ev,elec_affinity_ev,hardness,chem_potential,electrophil_index,num_delta_13C,num_delta_1H,...,nmr_dict_code_25,nmr_dict_code_26,nmr_dict_code_27,nmr_dict_code_28,nmr_dict_code_29,nmr_dict_code_30,nmr_dict_code_31,nmr_h_reconstruction_error,nmr_c_reconstruction_error,nmr_total_reconstruction_error
count,9599.000000,9599.000000,9599.000000,9599.000000,9599.000000,9599.000000,9599.000000,9599.000000,9599.000000,9599.000000,...,9.599000e+03,9.599000e+03,9.599000e+03,9.599000e+03,9.599000e+03,9.599000e+03,9.599000e+03,9599.000000,9599.000000,9599.000000
mean,-8.131548,0.618461,8.750010,8.131548,-0.618461,4.375005,-3.756544,1.677990,17.490676,9.188145,...,1.960592e+00,2.062769e+00,1.887041e+00,1.827203e+00,1.656094e+00,1.740577e+00,1.794937e+00,0.116879,0.146913,0.263793
std,0.599081,0.825669,0.979253,0.599081,0.825669,0.489626,0.529698,0.532415,8.773854,3.373935,...,3.051059e+00,3.012527e+00,2.999331e+00,3.076970e+00,3.318095e+00,3.721486e+00,3.077676e+00,0.037960,0.034320,0.065359
min,-10.421965,-2.589709,4.541038,6.167735,-3.782384,2.270519,-6.025147,0.290843,4.000000,3.000000,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.030093,0.077428,0.124998
25%,-8.533358,0.046259,8.084642,7.706403,-1.114035,4.042321,-4.102866,1.301344,11.000000,7.000000,...,3.935056e-22,4.132429e-07,1.394548e-34,3.974382e-29,3.113616e-37,1.724310e-26,1.353012e-34,0.090098,0.122263,0.216335
50%,-8.091309,0.537153,8.608053,8.091309,-0.537153,4.304027,-3.759254,1.645517,16.000000,9.000000,...,4.346398e-02,7.998250e-01,5.558867e-04,6.267794e-12,1.854906e-17,3.822141e-19,1.055822e-04,0.110193,0.139504,0.251012
75%,-7.706403,1.114035,9.271467,8.533358,-0.046259,4.635733,-3.412377,2.017495,21.000000,11.000000,...,3.030533e+00,3.088303e+00,2.822106e+00,2.870152e+00,2.328757e+00,2.037020e+00,2.686609e+00,0.136075,0.165022,0.297939
max,-6.167735,3.782384,13.547466,10.421965,2.589709,6.773733,-1.766564,5.283517,73.000000,23.000000,...,3.336768e+01,3.113490e+01,2.461790e+01,3.355259e+01,3.805479e+01,3.674381e+01,3.810706e+01,0.315666,0.372549,0.613693